---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmak
  labels:
    app: cmak
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cmak
  template:
    metadata:
      labels:
        app: cmak
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: cmak
          image: hlebalbau/kafka-manager:latest
          ports:
            - containerPort: 9000
          imagePullPolicy: IfNotPresent
          env:
            - name: ZK_HOSTS
              value: {{ .Values.env.scram.zookeeper }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-client-tester
  labels:
    app: kafka-client-tester
    component: service
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: kafka-client-tester
    component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client-tester
  labels:
    app: kafka-client-tester
    component: service
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka-client-tester
      component: service
  template:
    metadata:
      labels:
        app: kafka-client-tester
        component: service
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - image: golang:1.16.5
          name: kafka-client-tester
          command: [ "/bin/sh" ]
          args: [ "-c", "tail -f /dev/null" ]
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-go
  labels:
    app: kafka-consumer-go
    component: service
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: kafka-consumer-go
    component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-go
  labels:
    app: kafka-consumer-go
    component: service
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka-consumer-go
      component: service
  template:
    metadata:
      labels:
        app: kafka-consumer-go
        component: service
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - image: garystafford/kafka-consumer-go:1.0.0
          name: kafka-consumer-go
          ports:
            - containerPort: {{ .Values.image.ports.containerPort }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: TOPIC
              value: "foo-topic"
            - name: GROUP
              value: "consumer-group-A"
            - name: BROKER1
              value: {{ .Values.env.broker1 }}
            - name: BROKER2
              value: {{ .Values.env.broker2 }}
            - name: BROKER3
              value: {{ .Values.env.broker3 }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-go
  labels:
    app: kafka-producer-go
    component: service
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: kafka-producer-go
    component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-go
  labels:
    app: kafka-producer-go
    component: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-go
      component: service
  template:
    metadata:
      labels:
        app: kafka-producer-go
        component: service
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - image: garystafford/kafka-producer-go:1.0.2
          name: kafka-producer-go
          ports:
            - containerPort: {{ .Values.image.ports.containerPort }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: TOPIC
              value: "foo-topic"
            - name: GROUP
              value: "consumer-group-A"
            - name: BROKER1
              value: {{ .Values.env.broker1 }}
            - name: BROKER2
              value: {{ .Values.env.broker2 }}
            - name: BROKER3
              value: {{ .Values.env.broker3 }}
